[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "record fan obtain menu spoon length chicken olympic fantasy primary opera project reveal culture nephew crash organ security script faculty bullet have world drum"
